-- Presentation View: {{ presentation_name }}
-- Description: {{ description }}
-- Group: {{ group }}
-- Type: {{ type }}
-- Generated by PresentationRenderer

CREATE {% if replace_objects %}OR REPLACE VIEW{% else %}VIEW IF NOT EXISTS{% endif %} {{ presentation_database | upper }}.{{ presentation_schema | upper }}.{{ presentation_name | upper }}
AS
{% if join_info.ctes and join_info.ctes | length > 0 %}
WITH
{%- for cte in join_info.ctes %}
  {{ cte.name }} AS (
    SELECT t.*
    FROM {{ cte.source_full_name }} t
    QUALIFY ROW_NUMBER() OVER (
      PARTITION BY {% for pk in cte.partition_by %}{{ pk }}{% if not loop.last %}, {% endif %}{% endfor %}
      ORDER BY {{ cte.order_by }}
    ) = 1
  ){% if not loop.last %},
{% endif %}
{%- endfor %}
{% endif %}
SELECT
{%- for column in join_info.columns %}
    {{ column.expression }} AS {{ column.alias | upper }}{% if column.description %} COMMENT '{{ column.description }}'{% endif %}{% if not loop.last %},{% endif %}
{%- endfor %}
FROM {{ join_info.primary_table.full_name }} {{ join_info.primary_table.alias }}
{%- for join in join_info.joins %}
{{ join }}
{%- endfor %}
;

-- Add view metadata comment
COMMENT ON VIEW {{ presentation_database | upper }}.{{ presentation_schema | upper }}.{{ presentation_name | upper }} IS 
'{{ description }} (Group: {{ group }}, Type: {{ type }})';
