-- Dimension View: {{ dimension_name }}
-- Description: {{ description }}
-- Group: {{ group }}
-- Type: {{ type }}
-- Generated by DimensionRenderer

{#-
Inputs expected (similar to create_presentation_view.sql):
- replace_objects: boolean
- dimension_database: string
- dimension_schema: string
- dimension_name: string
- description, group, type: strings
- source.attribute_table: { database, schema, name, source, node (dimension entity), attr_node (attribute table primary), attr_node_hk, dimension_node_hk }
- columns: array of { name, type, description?, expression? }
-#}

{#- Build select list -#}
{%- set selected_columns = columns -%}
{%- set col_exprs = [] -%}
{%- for col in selected_columns -%}
  {%- if col.expression -%}
    {%- set _ = col_exprs.append(col.expression ~ " AS " ~ (col.alias or col.name) | upper) -%}
  {%- else -%}
    {%- set _ = col_exprs.append(((col.alias or col.name) | upper)) -%}
  {%- endif -%}
{%- endfor -%}

{# Render LOAD view (with change detection and SCD2 dates) #}
CREATE {% if replace_objects %}OR REPLACE VIEW{% else %}VIEW IF NOT EXISTS{% endif %} {{ dimension_database | upper }}.{{ dimension_schema | upper }}.V_DIM_{{ dimension_name | upper }}_LOAD
AS
WITH dimension_data AS (
  SELECT
    {%- if source.attribute_table.attr_node == source.attribute_table.dimension_node %}
    a.{{ source.attribute_table.dimension_node_hk }}
    {%- else %}
    n.{{ source.attribute_table.dimension_node_hk }},
    a.{{ source.attribute_table.attr_node_hk }}
    {%- endif %}
    {%- for expr in col_exprs %},
    a.{{ expr }}
    {%- endfor %},
    a.INGEST_TIME AS EFFECTIVE_FROM_DATE,
    a.LOAD_TIME,
    a.INGEST_TIME,
    a.LOADED_FROM,
  SHA2_BINARY(CONCAT_WS('||',
    {%- for col in selected_columns %}
    COALESCE({% if col.expression %}a.{{ col.expression }}{% else %}a.{{ col.name | upper }}{% endif %}::TEXT, '^^'){% if not loop.last %},{% endif %}
    {%- endfor %}
  )) AS DIMENSION_HASH
  FROM {{ source.attribute_table.database | upper }}.{{ source.attribute_table.schema | upper }}.ATTR_{{ source.attribute_table.attr_node | upper }}_{{ source.attribute_table.name | upper }}_{{ source.attribute_table.source | upper }} a
  {%- if source.attribute_table.attr_node != source.attribute_table.dimension_node %}
  INNER JOIN {{ source.attribute_table.database | upper }}.{{ source.attribute_table.schema | upper }}.EDGE_{{ source.attribute_table.attr_node | upper }}_{{ source.attribute_table.dimension_node | upper }} e
    ON a.{{ source.attribute_table.attr_node_hk }} = e.{{ source.attribute_table.attr_node_hk }}
  INNER JOIN {{ source.attribute_table.database | upper }}.{{ source.attribute_table.schema | upper }}.NODE_{{ source.attribute_table.dimension_node | upper }} n
    ON e.{{ source.attribute_table.dimension_node_hk }} = n.{{ source.attribute_table.dimension_node_hk }}
  {%- endif %}
  WHERE a.INGEST_TIME IS NOT NULL
  QUALIFY NOT(EQUAL_NULL(DIMENSION_HASH, LAG(DIMENSION_HASH) OVER (PARTITION BY {% if source.attribute_table.attr_node == source.attribute_table.dimension_node %}a{% else %}n{% endif %}.{{ source.attribute_table.dimension_node_hk }} ORDER BY EFFECTIVE_FROM_DATE)))
),

ranges AS (
  SELECT
    *,
    COALESCE(
      TIMESTAMPADD(MILLISECOND, -1, LEAD(EFFECTIVE_FROM_DATE) OVER (
        PARTITION BY {{ source.attribute_table.dimension_node_hk }}
        ORDER BY EFFECTIVE_FROM_DATE)),
      TO_TIMESTAMP('2099-12-31 23:59:59')
    ) AS EFFECTIVE_TO_DATE,
    CASE 
      WHEN EFFECTIVE_TO_DATE = TO_TIMESTAMP('2099-12-31 23:59:59') THEN TRUE 
      ELSE FALSE 
    END AS IS_CURRENT
  FROM dimension_data
)
SELECT
  {{ source.attribute_table.dimension_node_hk }}
  {%- for col in selected_columns %},
  {{ (col.alias or col.name) | upper }}
  {%- endfor %},
  DIMENSION_HASH,
  EFFECTIVE_FROM_DATE,
  EFFECTIVE_TO_DATE,
  IS_CURRENT,
  LOAD_TIME,
  INGEST_TIME,
  LOADED_FROM
FROM ranges
;

{# Render CURRENT view #}
CREATE {% if replace_objects %}OR REPLACE VIEW{% else %}VIEW IF NOT EXISTS{% endif %} {{ dimension_database | upper }}.{{ dimension_schema | upper }}.V_DIM_{{ dimension_name | upper }}_CURRENT
AS
SELECT
  {{ source.attribute_table.dimension_node_hk }}
  {%- for col in selected_columns %},
  {{ (col.alias or col.name) | upper }}
  {%- endfor %},
  EFFECTIVE_FROM_DATE,
  EFFECTIVE_TO_DATE,
  LOAD_TIME,
  INGEST_TIME,
  LOADED_FROM
FROM {{ dimension_database | upper }}.{{ dimension_schema | upper }}.V_DIM_{{ dimension_name | upper }}_LOAD
WHERE IS_CURRENT = TRUE
;

-- Add view metadata comment
COMMENT ON VIEW {{ dimension_database | upper }}.{{ dimension_schema | upper }}.V_DIM_{{ dimension_name | upper }}_LOAD IS 
'{{ description }} (Group: {{ group }}, Type: {{ type }})';

COMMENT ON VIEW {{ dimension_database | upper }}.{{ dimension_schema | upper }}.V_DIM_{{ dimension_name | upper }}_CURRENT IS 
'{{ description }} - current (Group: {{ group }}, Type: {{ type }})';


