-- Fact View: {{ fact_name }}
-- Description: {{ description }}
-- Group: {{ group }}
-- Generated by DimensionalModelRenderer

{#-
Inputs expected:
- replace_objects: boolean
- model_database, model_schema
- fact_name, description, group
- bridge_pattern: optional boolean for bridge pattern
- edges: array of { name }
- join_keys: optional array entries under edges[0].join_keys with edge1/edge2 indices and hks
- attributes.attribute_table { database, schema, name, source, primary_hk }
- columns: array of { name, type, expression?, alias? }
-#}

{%- set selected_columns = columns %}

CREATE {% if replace_objects %}OR REPLACE VIEW{% else %}VIEW IF NOT EXISTS{% endif %} {{ model_database | upper }}.{{ model_schema | upper }}.V_FACT_{{ fact_name | upper }}
AS
{%- if bridge_pattern %}
With 
attr as(
SELECT * from {{ attributes.attribute_table.database.lower() }}.{{ attributes.attribute_table.schema.lower() }}.attr_{{ attributes.attribute_table.name.lower() }}_{{ attributes.attribute_table.source.lower() }}
),

attr_hk as(
select distinct {{ attributes.attribute_table.primary_hk }} from attr
),

bridge as(
select 
/* HK from attribute table */
    attr_hk.{{ attributes.attribute_table.primary_hk }},
    /* primary node from first edge */
    -- edge_{{ edges[0].name.lower() }}.{{ attributes.attribute_table.primary_hk }}, 
    /* secondary nodes */
{%- set secondary_hks = [] -%}
{%- set collected_hk_names = [] -%}
{%- for edge in edges -%}
{%- set alias = 'edge_' ~ edge.name.lower() -%}
{%- for hk in edge.hash_keys -%}
{%- if hk != attributes.attribute_table.primary_hk and hk not in collected_hk_names -%}
{%- set _ = secondary_hks.append(alias ~ '.' ~ hk) -%}
{%- set _ = collected_hk_names.append(hk) -%}
{%- endif -%}
{%- endfor -%}
{%- endfor -%}
{%- for hk in secondary_hks %}
    {{ hk }}{%- if not loop.last %},{% endif %}
{%- endfor %}
from 
attr_hk
left join
{{ attributes.attribute_table.database.lower() }}.{{ attributes.attribute_table.schema.lower() }}.edge_{{ edges[0].name.lower() }} 
on attr_hk.{{ attributes.attribute_table.primary_hk }} = edge_{{ edges[0].name.lower() }}.{{ attributes.attribute_table.primary_hk }}
{%- for edge in edges[1:] -%}
{%- set alias = 'edge_' ~ edge.name.lower() %}
{%- set current_edge_idx = loop.index + 1 %}
{%- set join_conditions = [] -%}
{%- for join in join_keys | default([]) -%}
{%- if join.edge2_index == current_edge_idx -%}
{%- set edge1_alias = 'edge_' ~ edges[join.edge1_index - 1].name.lower() -%}
{%- set condition = edge1_alias ~ '.' ~ join.edge1_hk ~ ' = ' ~ alias ~ '.' ~ join.edge2_hk -%}
{%- if condition not in join_conditions -%}
{%- set _ = join_conditions.append(condition) -%}
{%- endif -%}
{%- endif -%}
{%- endfor -%}
{%- if join_conditions | length > 0 %}
left join
{{ attributes.attribute_table.database.lower() }}.{{ attributes.attribute_table.schema.lower() }}.edge_{{ edge.name.lower() }} on {{ join_conditions | join(' AND ') }}
{%- else %}
left join
{{ attributes.attribute_table.database.lower() }}.{{ attributes.attribute_table.schema.lower() }}.edge_{{ edge.name.lower() }} on edge_{{ edges[0].name.lower() }}.{{ attributes.attribute_table.primary_hk }} = {{ alias }}.{{ attributes.attribute_table.primary_hk }}
{%- endif -%}
{%- endfor %}
),

fact as(
Select 
    bridge.{{ attributes.attribute_table.primary_hk }},
{%- for hk in secondary_hks %}
    bridge.{{ hk.split('.')[-1] }},
{%- endfor %}
{%- for col in selected_columns %}
    attr.{{ (col.alias or col.name) | upper }},
{%- endfor %}
    attr.INGEST_TIME
from bridge
JOIN
attr on bridge.{{ attributes.attribute_table.primary_hk }} = attr.{{ attributes.attribute_table.primary_hk }}
)

select * from fact
{%- else %}
{#- Legacy non-bridge pattern -#}
{#- Precompute edge hash key projections to avoid parent/parentloop usage -#}
{%- set join_key_ids = [] -%}
{%- for join in join_keys | default([]) -%}
  {%- set _ = join_key_ids.append((join.edge1_index|string) ~ '|' ~ join.edge1_hk) -%}
  {%- set _ = join_key_ids.append((join.edge2_index|string) ~ '|' ~ join.edge2_hk) -%}
{%- endfor -%}

{%- set hk_selects = [] -%}
{%- for edge in edges -%}
  {%- set alias = 'e' ~ loop.index -%}
  {%- set edge_index = loop.index -%}
  {%- for hk in edge.hash_keys -%}
    {%- set hk_id = (edge_index|string) ~ '|' ~ hk -%}
    {%- if hk_id in join_key_ids -%}
      {%- set _ = hk_selects.append(alias ~ '.' ~ hk ~ ' AS ' ~ (alias | upper) ~ '_' ~ hk) -%}
    {%- else -%}
      {%- set _ = hk_selects.append(alias ~ '.' ~ hk) -%}
    {%- endif -%}
  {%- endfor -%}
{%- endfor %}
SELECT
  {{ hk_selects | join(',\n  ') }}
  {%- for col in selected_columns %}
  , a.{{ (col.alias or col.name) | upper }}
  {%- endfor %}
  , a.INGEST_TIME AS EFFECTIVE_DATE
  , a.LOAD_TIME
  , a.INGEST_TIME
  , a.LOADED_FROM
FROM
  {% for edge in edges -%}
  {%- set i = loop.index -%}
  {%- if i == 1 -%}
  {{ model_database | upper }}.{{ model_schema | upper }}.EDGE_{{ edge.name | upper }} e{{ i }}
  {%- else -%}
  {%- set conds = [] -%}
  {%- for join in join_keys | default([]) -%}
    {%- if join.edge2_index == i -%}
      {%- set _ = conds.append('e' ~ join.edge1_index ~ '.' ~ join.edge1_hk ~ ' = e' ~ join.edge2_index ~ '.' ~ join.edge2_hk) -%}
    {%- endif -%}
  {%- endfor %}
  INNER JOIN {{ model_database | upper }}.{{ model_schema | upper }}.EDGE_{{ edge.name | upper }} e{{ i }}
  {%- if conds | length > 0 %}
  ON {{ conds | join(' AND ') }}
  {%- endif -%}
  {%- endif -%}
  {%- endfor %}
  INNER JOIN {{ attributes.attribute_table.database | upper }}.{{ attributes.attribute_table.schema | upper }}.ATTR_{{ attributes.attribute_table.name | upper }}_{{ attributes.attribute_table.source | upper }} a
  ON e{{ attributes.attribute_table.edge_index }}.{{ attributes.attribute_table.edge_hk }} = a.{{ attributes.attribute_table.attr_hk }}
WHERE a.INGEST_TIME IS NOT NULL
{%- endif %}
;

