-- Database Deployment Script
-- Database: {{ database_name | upper }}
-- Generated by Unified Honey Engine

{% if drop_existing %}
-- Drop existing database if requested
DROP DATABASE IF EXISTS {{ database_name | upper }};
{% endif %}

-- Create database
CREATE DATABASE IF NOT EXISTS {{ database_name | upper }};

-- Create schemas
{% for layer in layers %}
CREATE SCHEMA IF NOT EXISTS {{ database_name | upper }}.{{ layer.name | upper }};
ALTER SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} SET COMMENT = '{{ layer.description }}';
{% endfor %}

{% if role_name %}
-- Create role for database access
CREATE ROLE IF NOT EXISTS {{ role_name | upper }};

-- Grant all privileges on the database
GRANT ALL PRIVILEGES ON DATABASE {{ database_name | upper }} TO ROLE {{ role_name | upper }};

-- Grant all privileges on all schemas
{% for layer in layers %}
GRANT ALL PRIVILEGES ON SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
{% endfor %}

-- Grant future object privileges per schema
{% for layer in layers %}
-- Core data objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE MATERIALIZED VIEWS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE TASKS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT ALL PRIVILEGES ON FUTURE PIPES IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
-- Code objects typically require USAGE
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA {{ database_name | upper }}.{{ layer.name | upper }} TO ROLE {{ role_name | upper }};
{% endfor %}
{% endif %}
