-- Full Refresh Multi-Table Insert for {{ name | upper }}
-- Source: {{ source | upper }}
-- Type: {{ type | upper }}
-- Generated by SQLRenderer (Full Refresh Mode)

-- Truncate all target tables first
{%- set node = primary_node.node | upper %}
TRUNCATE TABLE {{ target.database }}.{{ target.schema }}.NODE_{{ node }};

{%- for key in secondary_nodes %}
{%- set knode = key.node | upper %}
{%- if key.load != false %}
TRUNCATE TABLE {{ target.database }}.{{ target.schema }}.NODE_{{ knode }};
{%- endif %}
{%- endfor %}

{%- for key in secondary_nodes %}
{%- set knode = key.node | upper %}
TRUNCATE TABLE {{ target.database }}.{{ target.schema }}.EDGE_{{ node }}_{{ knode }};
{%- endfor %}

TRUNCATE TABLE {{ target.database }}.{{ target.schema }}.ATTR_{{ node }}_{{ name | upper }}_{{ source | upper }};

-- Multi-Table Insert with deduplication using window functions
INSERT ALL
-- Insert into primary node ({{ primary_node.node }}) - first occurrence per HK only
WHEN (node_{{ node }}_rn = 1) THEN
  INTO {{ target.database }}.{{ target.schema }}.NODE_{{ node }}
  (
    {{ node }}_HK,
    {{ node }}_CK,
    LOAD_TIME,
    LOADED_FROM
  )
  VALUES (
    SRC_{{ node }}_HK,
    SRC_{{ node }}_CK,
    SRC_LOAD_TIME,
    SRC_LOADED_FROM
  )
{%- for key in secondary_nodes %}
{%- set knode = key.node | upper %}
{%- if key.load != false %}

-- Insert into secondary node no{{ loop.index }} ({{ key.node }}) - first occurrence per HK only
WHEN (node_{{ knode }}_rn = 1) THEN
  INTO {{ target.database }}.{{ target.schema }}.NODE_{{ knode }}
  (
    {{ knode }}_HK,
    {{ knode }}_CK,
    LOAD_TIME,
    LOADED_FROM
  )
  VALUES (
    SRC_{{ knode }}_HK,
    SRC_{{ knode }}_CK,
    SRC_LOAD_TIME,
    SRC_LOADED_FROM
  )
{%- endif %}

-- Insert into edge {{ node }} -> {{ key.node }} - first occurrence per EK only
WHEN (edge_{{ node }}_{{ knode }}_rn = 1) THEN
  INTO {{ target.database }}.{{ target.schema }}.EDGE_{{ node }}_{{ knode }}
  (
    {{ node }}_{{ knode }}_EK,
    {{ node }}_HK,
    {{ knode }}_HK,
    LOAD_TIME,
    INGEST_TIME,
    LOADED_FROM
  )
  VALUES (
    SRC_{{ node }}_{{ knode }}_EK,
    SRC_{{ node }}_HK,
    SRC_{{ knode }}_HK,
    SRC_LOAD_TIME,
    SRC_INGEST_TIME,
    SRC_LOADED_FROM
  )
{%- endfor %}

-- Insert into attributes - all records (no deduplication)
INTO {{ target.database }}.{{ target.schema }}.ATTR_{{ node }}_{{ name | upper }}_{{ source | upper }}
(
  {{ node }}_HK,
  {%- for col in columns %}
  {{ col.target | upper }},
  {%- endfor %} 
  IS_DELETED,
  HASH_DIFF,
  LOAD_TIME,
  INGEST_TIME,
  LOADED_FROM
)
VALUES (
  SRC_{{ node }}_HK,
  {%- for col in columns %}
  SRC_{{ col.target | upper }},
  {%- endfor %} 
  SRC_IS_DELETED,
  SRC_HASH_DIFF,
  SRC_LOAD_TIME,
  SRC_INGEST_TIME,
  SRC_LOADED_FROM
)

-- Select with computed keys and row numbers for deduplication
SELECT
    -- Primary Hash
    SHA1_BINARY({{ hash_expr(composite_expr(primary_node.name)) }}) AS SRC_{{ node }}_HK,
    {{ composite_expr(primary_node.name) }} AS SRC_{{ node }}_CK,
    ROW_NUMBER() OVER (PARTITION BY SHA1_BINARY({{ hash_expr(composite_expr(primary_node.name)) }}) ORDER BY SRC.{{ ingest_time | upper }}, SYSDATE()) AS node_{{ node }}_rn,
    -- Secondary Keys
    {%- for key in secondary_nodes %}
    {%- set knode = key.node | upper  %}
    SHA1_BINARY({{ hash_expr(composite_expr(key.name)) }}) AS SRC_{{ knode }}_HK,
    {{ composite_expr(key.name) }} AS SRC_{{ knode }}_CK,
    {%- if key.load != false %}
    ROW_NUMBER() OVER (PARTITION BY SHA1_BINARY({{ hash_expr(composite_expr(key.name)) }}) ORDER BY SRC.{{ ingest_time | upper }}, SYSDATE()) AS node_{{ knode }}_rn,
    {%- endif %}
    SHA1_BINARY(
      UPPER(
        ARRAY_TO_STRING(
          ARRAY_CONSTRUCT(
            {{ hash_expr(composite_expr(primary_node.name)) }},
            {{ hash_expr(composite_expr(key.name)) }}
          ),
        '^'
        )
      )
    ) AS SRC_{{ node }}_{{ knode }}_EK,
    ROW_NUMBER() OVER (PARTITION BY SHA1_BINARY(UPPER(ARRAY_TO_STRING(ARRAY_CONSTRUCT({{ hash_expr(composite_expr(primary_node.name)) }},{{ hash_expr(composite_expr(key.name)) }}),'^'))) ORDER BY SRC.{{ ingest_time | upper }}, SYSDATE()) AS edge_{{ node }}_{{ knode }}_rn,
    {%- endfor %}
    -- Data Cols
    {%- for col in columns %}
    SRC.{{ col.binding | upper }} AS SRC_{{ col.target | upper }},
    {%- endfor %}
    -- IS_DELETED
    SRC.IS_DELETED AS SRC_IS_DELETED,
    -- Dates
    SYSDATE() AS SRC_LOAD_TIME,
    SRC.{{ ingest_time | upper }} AS SRC_INGEST_TIME,
    '{{ name | upper }}' AS SRC_LOADED_FROM,
    -- Hash Diff
    SHA1_BINARY(
      ARRAY_TO_STRING(
        ARRAY_CONSTRUCT(
          {{ hash_expr(composite_expr(primary_node.name)) }},
          {%- for key in secondary_nodes %}
          {{ hash_expr(composite_expr(key.name)) }},
          {%- endfor %}
          {%- for col in columns %}
          {{ hash_expr('SRC.' + col.binding) }}{% if not loop.last %},{% endif %}
          {%- endfor %}
        ),
        '^'
      )
    ) AS SRC_HASH_DIFF
FROM {{ stage.database | upper }}.{{ stage.schema | upper }}.STG_{{ name | upper }}_{{ source | upper }} SRC;
